language: rust

rust:
  - stable
  - beta
  - nightly
  
env:
  - FLAGS="--no-default-features"
  - FLAGS="--no-default-features --features num"
  - FLAGS="--no-default-features --features use_serde"
  - FLAGS="--features std"
  - FLAGS="--features num"
  - FLAGS="--features use_serde"
  - FLAGS="--features std --features num --features use_serde"
  - FLAGS="--features std --features use_serde"

script: cargo test $FLAGS
